version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'org.junit.jupiter:*'
        versions: ['>=6.0.0']
      - dependency-name: 'org.junit.platform:*'
        versions: [ '>=6.0.0' ]
    groups:
      all:
        patterns:
          - '*'
       # seems that split between prod & test deps is not implemented for gradle
       # dependency-type: production
